
CREATE TABLE parking (
    id UUID PRIMARY KEY,
    location VARCHAR(255) NOT NULL,
    capacity INT NOT NULL,
    occupied INT NOT NULL DEFAULT 0
);
INSERT INTO parking
(ID, LOCATION, CAPACIY, OCCUPIED)
VALUES(10001, 'ABC', 10, 5);
INSERT INTO parking
(ID, LOCATION, CAPACIY, OCCUPIED)
VALUES(10002, 'ABC', 10, 5);
INSERT INTO parking
(ID, LOCATION, CAPACIY, OCCUPIED)
VALUES(10003, 'ABC', 10, 5);
INSERT INTO parking
(ID, LOCATION, CAPACIY, OCCUPIED)
VALUES(10004, 'ABC', 10, 5);
INSERT INTO parking
(ID, LOCATION, CAPACIY, OCCUPIED)
VALUES(10005, 'ABC', 10, 5);